---
# https://taskfile.dev

version: '3'

vars:
  IMAGE_NAME: "ipxe-httpd"
  CONTAINER_NAME: "{{ .IMAGE_NAME }}"

tasks:

  update:
    desc: Install/Update Flask and Python packages
    cmds:
      - pip3 install --upgrade pip setuptools
      - pip3 install --upgrade -r requirements.txt

  build:
    desc: Build Docker image
    cmds:
      - docker build -t {{ .IMAGE_NAME }} -f Dockerfile .

  start:
    desc: Start Docker container
    cmds:
      - docker run --rm -d
                   -p 8080:8080
                   -v $(pwd)/ipxe/:/ipxe/
                   -v $(pwd)/config_local.json:/config_local.json
                   --name {{ .CONTAINER_NAME }}
                   {{ .IMAGE_NAME }}

  stop:
    desc: Stop Docker container
    cmds:
      - docker stop {{ .CONTAINER_NAME }}

  exec:
    desc: Execute shell inside container
    cmds:
      - docker exec -it {{ .CONTAINER_NAME }} sh

  logs:
    desc: Show container logs
    cmds:
      - docker logs {{ .CONTAINER_NAME }}

...
